spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

server:
  port: 8081
  servlet:
    context-path: "/api/v1"